wait for emulator

diff --git a/.github/workflows/e2e-android-detox.yml b/.github/workflows/e2e-android-detox.yml
--- a/.github/workflows/e2e-android-detox.yml
+++ b/.github/workflows/e2e-android-detox.yml
@@ -143,7 +143,19 @@ jobs:
 
         - name: Start AOSP Emulator
           run: |
-            nohup $ANDROID_HOME/emulator/emulator -avd ${AVD_NAME} -no-audio -no-window -no-snapshot > /dev/null 2>&1 &
+            nohup $ANDROID_HOME/emulator/emulator -avd ${AVD_NAME} -no-audio -no-window -no-snapshot -gpu swiftshader_indirect -verbose > emulator.log 2>&1 &
+            echo "Waiting for emulator to start..."
+            timeout=600 # 10 minutes timeout
+            while [[ $(adb devices | grep emulator | wc -l) -eq 0 ]]; do
+              sleep 5
+              timeout=$((timeout - 5))
+              if [[ $timeout -le 0 ]]; then
+                echo "Emulator failed to start within time limit."
+                cat emulator.log
+                exit 1
+              fi
+            done
+            echo "Emulator is up and running."
             adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
             adb shell settings put global window_animation_scale 0
             adb shell settings put global transition_animation_scale 0
